Add grid drag-and-drop support
onlook-dev/onlook pull request #634
Opened 2024-10-23 14:45 UTC by Ashutoshdas-dev

### Description

The code has been updated to support grid layouts in addition to the existing flex and block layout handling. This was achieved by modifying the moveStub function to detect grid layouts and apply specialized handling. Two new functions, findGridInsertionIndex and adjustStubPositionForGrid, were introduced to calculate insertion positions and correctly position the stub within grid cells, respectively. 

### What is the purpose of this pull request? 

- [X ] New feature
- [ ] Documentation update
- [ ] Bug fix
- [ ] Refactor
- [ ] Release
- [ ] Other

2024-10-23 15:19 UTC, Kitenite commented
Awesome, taking a look!

2024-10-23 20:25 UTC, Kitenite reviewed
This is working really well except for one small bug. I can't seem to place the element back to its original position. Can you confirm this?

https://github.com/user-attachments/assets/124e7ecc-18fe-44be-887a-0dd59cc95039

 This [playground repo ](https://github.com/onlook-dev/playground)might help with testing :)

2024-10-23 20:27 UTC, Kitenite requested changes
Marking this as request change for visibility

2024-10-24 06:02 UTC, Ashutoshdas-dev commented
hey @Kitenite working on the bug. updating it as soon as possible

2024-10-24 14:22 UTC, Ashutoshdas-dev commented
Hey @Kitenite the code has been updated please check and let me for more update

2024-10-24 14:33 UTC, Kitenite commented on app/electron/preload/webview/elements/move/stub.ts
> +    const parent = el.parentElement;
The original stub position is already created and stored here. The stub should be free to move anywhere regardless of its original position. There's already resolution logic for when an element is placed in its original location as you can see in the drag functionalities here. Let me know if this helps. 

https://github.com/onlook-dev/onlook/blob/cdbebe99f07a154ef5ea5d8a89b3edecce3e844f/app/electron/preload/webview/elements/move/drag.ts#L21

2024-10-24 14:33 UTC, Kitenite requested changes
I added some comments pointing to some existing logic for storing the original positon. Sorry if this wasn't included before :)

2024-10-25 11:09 UTC, closed without merging