UI Sanding
onlook-dev/onlook pull request #878
Opened 2024-12-11 00:23 UTC by drfarrell

### Description

Improvements to...
- Node tree – making it more obvious what elements belong to a component (purple text)
- Project Settings page – better typography, glossy background, better close button, and better text labels
- Project sub-menu dropdown – make this go away after the user has selected an item from the menu
- Inputs – made the quad-icon not cut-off on the sides, tightened the spacing of the accordions 

### What is the purpose of this pull request? 

- [X] New feature
- [ ] Documentation update
- [X] Bug fix
- [ ] Refactor
- [ ] Release
- [ ] Other

2024-12-11 00:23 UTC, drfarrell commented
I'm still going to work on this a bit – but just saving this here.

2024-12-12 18:54 UTC, Kitenite commented on apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
> +                                        onMouseDown={(e) => {
What's the intention here?

2024-12-12 19:12 UTC, Kitenite commented on apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
> +                                        onMouseDown={(e) => {
I guess select the node when it's toggled?

2024-12-12 19:13 UTC, Kitenite approved these changes
Looks good, feel free to merge it if the one question is intentional

2024-12-12 19:18 UTC, Kitenite requested changes
Actually, found a visual bug from the animation

https://github.com/user-attachments/assets/10011228-c524-4754-9320-1785a20b5624

2024-12-13 02:25 UTC, Kitenite commented on apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
> +        function hasComponentAncestor(node: NodeApi<LayerNode>): boolean {
This is a very expensive operation. With a large enough tree, the app will grind to a halt.

2024-12-13 02:46 UTC, Kitenite commented on apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
> +        function hasComponentAncestor(node: NodeApi<LayerNode>): boolean {
Fixed! Good thing too because I added some extra performance fix thanks to this.

2024-12-13 03:18 UTC, Kitenite approved these changes

2024-12-13 03:18 UTC, merged